const TILE_SIZE_VALUE = 100; 

const CONFIG = {

    BOT_RADIUS: 8,
    BOT_COLOR: 'magenta', 
    BOT_SPEED: 0.4,       
    BOT_HEALTH: 10,
    BOT_DETECTION_RADIUS: 120,
    BOT_CHASE_RADIUS: 100,
    BOT_ATTACK_DAMAGE: 10, 

    BOT_SPAWN_INTERVAL_MIN: 5000, 
    BOT_SPAWN_INTERVAL_MAX: 15000, 
    MAX_BOTS_ON_MAP: 10,          

    // Canvas & Grid
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    TILE_SIZE: TILE_SIZE_VALUE, 
    GRID_LINE_WIDTH: 3,
    ROAD_COLOR: '#202020',

    // Map Colors
    BUILDING_COLOR: '#000000',
    OPEN_SPACE_COLOR: '#00FF00',
    BASE_STATION_COLOR: '#00FFFF',
    CENTRAL_HUB_COLOR: '#FFA500',

    // Player
    PLAYER_RADIUS: 7,
    PLAYER_COLOR: '#FFFFFF',
    PLAYER_SPEED: 0.7,
    PLAYER_INITIAL_HEALTH: 100,
    PLAYER_SHOOT_COOLDOWN: 300,

    // Projectiles (Bullets)
    PROJECTILE_RADIUS: 4,
    PROJECTILE_COLOR: '#FF0000',
    PROJECTILE_SPEED: 5,

    // Surveillance Tower
    TOWER_COLOR: '#8B0000',

    TOWER_VISION_RADIUS: TILE_SIZE_VALUE / 2, 
    TOWER_VISION_COLOR: 'rgba(255, 0, 0, 0.3)',
    TOWER_VISION_ANGLE: Math.PI / 2, 
    TOWER_ROTATION_SPEED: 0.015,
    TOWER_DAMAGE_PER_SECOND: 2,
    TOWER_HEALTH: 30,

    // Keys & Shards
    KEY_COLOR: '#FFD700',
    KEY_RADIUS: 7,
    NUM_KEYS_TO_SPAWN: 5,
    SHARD_DECRYPTION_COST: 1,
    SYSTEM_HEALTH_RECOVERY_PER_SHARD: 20,
    MAX_SYSTEM_HEALTH: 100,
    INITIAL_SYSTEM_HEALTH: 100,
    SYSTEM_HEALTH_DECAY_RATE: 0.1,

    // Game Logic
    GAME_FPS: 60,
};
